// grid dummy data
var dummyData = {
    "Writing":"<ol style=\"text-align: left;\">"
    +"<li><a href=\"https://www.linkedin.com/pulse/my-data-story-dr-jayanti-prasad/\" target=\"dynamic\"> My data story</li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/data-science-jayanti-prasad-ph-d-/\" target=\"dynamic\"> Data Science </a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/covid-19-big-picture-jayanti-prasad-ph-d-/\" target=\"dynamic\"> Covid-19: The Big picture </a> </li>"
    +"<li><a href=\"https://medium.com/@prasad.jayanti/cognitive-bias-will-kill-more-indians-than-covid-19-5e5d968e2e9c\" target=\"dynamic\"> Cognitive Bias will kill more Indians than Covid-19</a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/how-draw-values-from-machine-learning-dr-jayanti-prasad/\" target=\"dynamic\"> How to draw values from Machine Learning</li> </a>"
    +"<li><a href=\"https://www.linkedin.com/pulse/ata-science-interview-so-common-jayanti-prasad-ph-d-/\" target=\"dynamic\">"
    +"A data science interview not so common </a> </li>" 
    +"<li><a href=\"https://www.linkedin.com/pulse/learn-data-science-one-month-technical-background-needed-prasad/\" target=\"dynamic\"> Learn data science in one month ! No technical background needed ! </a> </li>" 
    +"<li><a href=\"https://www.linkedin.com/pulse/how-do-you-learn-data-science-jayanti-prasad-ph-d-/\" target=\"dynamic\">"
    +"How do you learn data science ?"
    +"<li><a href=\"https://www.linkedin.com/pulse/learning-optimization-jayanti-prasad-ph-d-/\" target=\"dynamic\">"
    +"Learning and Optimization </a> </li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/existential-crisis-dr-jayanti-prasad/\" target=\"dynamic\">"
    +"Existential Crisis </a> </li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/data-science-checklist-dsc-130-dr-jayanti-prasad/\" target=\"dynamic\">"
    +"Data Science Checklist : DSC-130 </a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/power-ignorance-dr-jayanti-prasad/\" target=\"dynamic\">"
    +"The power of ignorance </a> </li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/data-biased-source-dr-jayanti-prasad/\" target=\"dynamic\">"
    +"The data biased at source </a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/big-code-dr-jayanti-prasad/\" target=\"dynamic\">"
    +"The Big Code </a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/has-google-really-built-first-general-purpose-quantum-prasad/\" target=\"dynamic\"> Has Google really built the first general purpose Quantum Computer ? </a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/nlp-ai-frontier-dr-jayanti-prasad/\" target=\"dynamic\">"
    +"NLP at frontier </a></li>"
    +"<li><a href=\"https://www.linkedin.com/pulse/your-business-ready-use-ai-dr-jayanti-prasad/\" target=\"dynamic\">"
    +" Is your business ready for the use of AI ?</a></li>"
    +"</ol>",
    "Medium":"https://medium.com/@prasad.jayanti",
    "Contact":"prasad.jayanti@gmail.com",
    "About":"<h2> Short Biography </h2> <p style=\"text-align: left\">"
    +"My name is Jayanti Prasad and I am a Physicist and data scientist."
    +"I did Ph.D in Physics (specialization in Astronomy & Astrophyics) from the "
    +"<a href=\"http://www.hri.res.in/\"> Harish-Chandra Research Institute Allhabad (India) </a>"
    +"in 2009. I have worked on problems in cosmology (galaxy formation and clustering,"
    +"N-body simulation, cosmic microwave background, early universe etc.), Radio Astronomy"
    +" and Gravational Waves. I was a post doctoral fellow at the National Centre for Astrophyics"
    +"(NCRA-TIFR) Pune from 2008 to 2010 and at the Inter-University Center for Astronomy"
    +" & Astrophysics (IUCAA) Pune from 2010 to 2013. I was a DST-SERB (Govt. of India) Young"
    +" scientist at IUCAA during 2013-2015. For a brief period of time, from 2015 to 2016, I also"
    +" worked at the Center for modeling and simulation (CMS) department of the Savitribai Phule"
    +" Pune University Pune. I joined the IUCAA again in 2016 as a Consulatant System"
    +" Administrator for the LIGO project."
    +" I was a member of the LIGO Scientific collaboartion (LSC) from 2012 to 2018"
    +" during this period many important discoveries were made by the collaboartion."
    +" I  resigned from IUCAA in 2018 to take a full time job of"
    +" data scientist at a software company Accelere Software (now Emobold Technologies) Pune in 2018."
    +" I resigned from the Embold Technology in late 2019 to work on some"
    +" Freelancing projects. I was one of the invited speakers of the <a href=\"https://bigdat2020.irdta.eu/\" target=\"dynamic\"> \"Big Data 2020\" </a> "
    +" meeting which took place in Ancona (Italy) between 13th and 18th January 2020.</p> <hr>",
    "Publications": "<h2> Publications (Astronomy & Astrophysics) </h2>"
+" <ol style=\"text-align: left;\">"
+" <br><li> Bagla, J. S., <b>Prasad, Jayanti </b> and  Ray, Suryadeep (2005) <br>"
+"  <a href=\"http://www3.interscience.wiley.com/journal/118689116/abstract\" target=\"dynamic\"> MNRAS, 360  194</a>,"
+" [<a href=\"http://arxiv.org/abs/astro-ph/0408429\" target=\"dynamic\"> astro-ph/0408429</a>] <br>"
+"  <i>  Gravitational collapse in an expanding background and the role of"
+"             substructure I: Planar collapse </i> </li>"
+""
+" <br><li>  Bagla, J. S., <b>Prasad, Jayanti </b> (2008) <br>"
+"  <a href=\"http://www3.interscience.wiley.com/journal/121659298/abstract\" target=\"dynamic\">MNRAS, 1365, 2966 </a>, "
+"  [<a href=\"http://arxiv.org/abs/0802.2796\" target=\"dynamic\">arXiv:0802.2796 [astro-ph]</a>] <br>"
+"  <i> Gravitational collapse in an expanding background and the role of"
+"   substructure II:    Excess power at small scales and its effect"
+"   of collapse of structures at larger scales. </i> </li>"
+""
+"  <br><li>  Bagla, J. S., <b>Prasad, Jayanti </b> (2006) <br>"
+"   <a href=\"http://www3.interscience.wiley.com/journal/118550149/abstract\" target=\"dynamic\">MNRAS, 370, 993</a>,"
+"[<a href=\"http://arxiv.org/abs/astro-ph/0601320\" target=\"dynamic\">astro-ph/0601320 </a>] <br>"
+"  <i>Effects of the size of cosmological N-Body simulations "
+"            on physical quantities -- I: Mass Function </i></li>"
+""
+"<br><li> Prasad, Jayanti (2007) <br>"
+"<a href=\"http://www.springerlink.com/content/4p46q5473332l641/\" target=\"dynamic\">J. Astrophys.Astron. 28, 117</a>, "
+"[<a href=\"http://arxiv.org/abs/astro-ph/0702557\"  target=\"dynamic\">astro-ph/0702557</a>]<br>"
+" <i>Effects of the size of cosmological N-Body simulations "
+"on physical quantities -- II: Halo Formation"
+" and Destruction rate </i> </li>"
+""
+"<br><li> J.S. Bagla, <b>Jayanti Prasad</b>, Nishikanta Khandai (2009)<br>"
+" <a href=\"http://mnras.oxfordjournals.org/content/395/2/918\" target=\"dynamic\"> MNRAS,395,918 </a>,"
+" [<a href=\"http://arxiv.org/abs/0804.1197\" target=\"dynamic\">arXiv:0804.1197 [astro-ph]</a>] <br>"
+"<i> Effects of the size of cosmological N-Body simulations on"
+"physical quantities - III: Skewness.</i> </li>"
+""
+"<br><li>"
+"Jayanti Prasad, Tarun Souradeep  (2012) <br>"
+"<a href=\"http://prd.aps.org/abstract/PRD/v85/i12/e123008\" target=\"dynamic\">Phys. Rev. D 85, 123008 (2012) </a>, "
+"[<a href=\"http://arxiv.org/abs/1108.5600\" target=\"dynamic\">arXiv:1108.5600v2 </a>] <br>"
+"<i> Cosmological parameter estimation using Particle Swarm Optimization (PSO) </i>"
+"</li>"
+""
+"<br><li> Jayanti Prasad and Jayaram Chengalur (2011) <br>"
+" <a href=\"http://www.springerlink.com/content/t16w72r356500980/\" target=\"dynamic\"> Experimental Astronomy </a>, "
+" [<a href=\"http://arxiv.org/abs/1111.6415\" target=\"dynamic\">arXiv: 1111.6415 </a>] <br>"
+"<i> FLAGCAL:A flagging and calibration package for radio interferometric data</i>"
+"</li>"
+""
+"<br><li>"
+"Abhik Ghosh, Jayanti Prasad, Somnath Bharadwaj, Sk. Saiyad Ali, Jayaram N. Chengalur (2012) <br>"
+"<a href=\"http://mnras.oxfordjournals.org/content/426/4/3295\" target=\"dynamic\"> MNRAS 426, 3295 </a>"
+"[<a href=\"http://arxiv.org/abs/1208.1617\" target=\"dynamic\">arXiv:1208.1617v1</a>]<br> "
+"<i> Characterizing Foreground for redshifted 21-cm radiation: 150 MHz GMRT observations </i>"
+"</li>"
+""
+"<br><li>"
+" N. D. R. Bhat, J. N. Chengalur, P. J. Cox, Y. Gupta, J. Prasad, J. Roy, M. Bailes, S. Burke-Spolaor, S. S. Kudale, W. van Straten (2013) <br>"
+" <a href=\"http://iopscience.iop.org/0067-0049/206/1/2/\" target=\"dynamic\"> ApJ.  Supp.  206, 2,   "
+" [<a href=\"http://arxiv.org/abs/1302.3418\" target=\"dynamic\">arXiv:1302.3418 </a> <br>"
+"<i>  Detection of fast transients with radio interferometric arrays</i>"
+"</li>"
+""
+"<br><li>"
+"Gaurav Goswami, Jayanti Prasad (2013) <br>"
+"<a href=\"http://prd.aps.org/abstract/PRD/v88/i2/e023522\" target=\"dynamic\"> Phys. Rev. D 88, 023522 (2013)</a>,"
+" [<a href=\"http://arxiv.org/abs/1303.4747\" target=\"dynamic\">arXiv:1303.4747v1 [astro-ph.CO] </a>"
+"<br> <i> Maximum entropy deconvolution of primordial power spectrum</i></li>"
+""
+"<br><li>"
+"Suratna Das, Gaurav Goswami,  Jayanti Prasad, Raghavan Rangarajan (2015) <br> "
+"<a href=\"https://iopscience.iop.org/article/10.1088/1475-7516/2015/06/001/meta\" target=\"dynamic\"> JCAP (2015) {\bf 06}, 001, </a>"
+", [<a href=\"http://arxiv.org/abs/1412.7093\" target=\"dynamic\"> arXiv:1412.7093 [astro-ph.CO]] </a> <br>"
+"<i> Revisiting a pre-inflationary radiation era and its effect on the CMB power spectrum </i> </li>."
+""
+""
+"<br><li> "
+"Asif Iqbal, Jayanti Prasad, Tarun Souradeep, Manzoor A. Malik (2015) <br> "
+"<a href=\"https://iopscience.iop.org/article/10.1088/1475-7516/2015/06/014/meta\" target=\"dynamic\">  JCAP (2015) 06, 014 </a> "
+", [<a href=\"http://arxiv.org/abs/1501.02647\" target=\"dynamic\"> arXiv:1501.02647 [astro-ph.CO]] </a> <br>"
+"<i> Joint Planck and WMAP Assessment of Low CMB Multipoles </i> </li>"
+""
+"<br><li>"
+"Suratna Das, Gaurav Goswami,  Jayanti Prasad , Raghavan Rangarajan, (2016) <br> "
+"<a href=\"https://journals.aps.org/prd/abstract/10.1103/PhysRevD.93.023516\" target=\"dynamic\"> Phys. Rev. D (2016),  93, 023516 </a> , [<a href=\"http://arxiv.org/abs/1506.04808\" target=\"dynamic\"> arXiv:1506.04808 [hep-ph]] </a><br>"
+"<i>Constraints on just enough inflation preceded by a thermal era </i></li>"
+""
+"<br><li>"
+"Mansi Dhuria, Gaurav Goswami, Jayanti Prasad (2017) <br>"
+"<a href=\"https://journals.aps.org/prd/abstract/10.1103/PhysRevD.96.083529\" target=\"dynamic\"> Phys. Rev. D (2017)  96, 083529 </a>  , [<a href=\"https://arxiv.org/abs/1705.11071\" targte=\"dynamic\"> arXiv:1705.11071 [hep-ph]] </a> <br> "
+"<i>Extranatural Inflation Redux </i></li>"
+""
+""
+"<br><li>"
+"Richa Arya, Arnab Dasgupta, Gaurav Goswami, Jayanti Prasad, Raghavan Rangarajan (2018) <br>"
+"<a href=\"https://iopscience.iop.org/article/10.1088/1475-7516/2018/02/043/meta\" target=\"dynamic\"> JCAP  (2018)  02 043, </a> "
+"[<a href=\"https://arxiv.org/abs/1710.11109\" target=\"dynamic\"> arXiv:1710.11109 [astro-ph.CO]] </a><br>"
+"<i>Revisiting CMB constraints on Warm Inflation </i></li>"
+""
+"</ol>"
+"</div>"
+""
+"<h3> Some other important Publications (with LIGO): </h3>"
+"<ol style=\"text-align: left;\">"
+""
+"<br><li>"
+"Abbott et. al. (The LIGO Scientific Collaboration and the Virgo Collaboration), 2016 <br> "
+"Phys. Rev. Lett. 116, 061102 (2016), [<A HREF=\"http://arxiv.org/abs/1602.03837\">[arXiv:1602.03837 [gr-qc]]</a><br>"
+"<i>Observation of Gravitational Waves from a Binary Black Hole Merger </i> [MAJOR DISCOVERY]"
+"(see New Yorker's article <a href=\"https://www.newyorker.com/tech/annals-of-technology/gravitational-waves-exist-heres-how-scientists-finally-found-them\"  target=\"dynamic\"> here </a></li>"
+""
+"<br><li>"
+"B.P. Abbott et al. (LIGO Scientific Collaboration, Virgo Collaboration), 2017 <br>"
+"<a href=\"https://www.nature.com/nature/journal/v551/n7678/full/nature24471.html\" target=\"dynamic\"> Nature 551, 8588 (02 November 2017) </a>  [<A HREF=\"https://arxiv.org/abs/1710.05835\">arXiv:1710.05835 [astro-ph.CO]]</A>"
+"<br> <i> A gravitational-wave standard siren measurement of the Hubble constant. </a></li>"
+""
+"For my compleate list of publications please click <a href=\"docs/jayanti-pub-2020.pdf\" target=\"dynamic\"> Here </a>"
+"</ol>",
"Presentations":"<ul style=\"text-align: left;\">"
+"<h2> General Cosmology </h2>"
+"<ul style=\"text-align: left;\">"
+"<li><a href=\"docs/talks/State-of-the-Universe.pdf\" target=\"dynamic\"> State of the universe </a></li>"
+"<li><a href=\"docs/talks/Story-of-the-universe.pdf\" target=\"dynamic\"> Story of the Universe </a></li>"
+"<li><a href=\"https://www.youtube.com/watch?v=-oTzI1rPaW8\" target=\"dynamic\"> Story of the Universe (Video) </a></li>"
+"</ul>"
+"<h2> NBODY simulations </h2><ul style=\"text-align: left;\">"
+"<li><a href=\"docs/talks/nbody.pdf\" target=\"dynamic\"> NBODY  </a></li>"
+"<li><a href=\"docs/talks/nbody_iitk.pdf\" target=\"dynamic\"> NBODY (IITK) </a></li>"
+"<li><a href=\"docs/talks/tifr_talk.pdf\" target=\"dynamic\"> NBODY (TIFR) </a></li>"
+"</ul>"
+"<h2> CMBR </h2><ul style=\"text-align: left;\">"
+"<li><a href=\"docs/talks/cmb1.pdf\" target=\"dynamic\"> CMB  1 </a> </li>"
+"<li><a href=\"docs/talks/cmb2.pdf\" target=\"dynamic\"> CMB  2 </a> </li>"
+"<li><a href=\"docs/talks/fisher.pdf\" target=\"dynamic\"> Fisher information </a> </li>"
+"<li><a href=\"docs/talks/cmb-like1.pdf\" target=\"dynamic\"> CMB Likelihood 1 </a> </li>"
+"<li><a href=\"docs/talks/cmb-like2.pdf\" target=\"dynamic\"> CMB Likelihood 2 </a> </li>"
+"<li><a href=\"docs/talks/planck2015-p1-overview.pdf\" target=\"dynamic\"> Planck 1 </a> </li>"
+"<li><a href=\"docs/talks/planck2015-p2-params.pdf\" target=\"dynamic\"> Planck 2 </a> </li>"
+"<li><a href=\"docs/talks/iucaa_review.pdf\" target=\"dynamic\"> Primordial power spectrum  </a> </li>"
+"<li><a href=\"docs/talks/pso.pdf\" target=\"dynamic\"> PSO  </a> </li>"
+"<li> <a href=\"docs/talks/cmb-part1.pdf\"> CMB Part 1 </a> (Lecture course I gave BITS Pilani) <br>"
+"<li> <a href=\"docs/talks/cmb-part2.pdf\"> CMB Part 2 </a> (Lecture course I gave BITS Pilani) <br>"
+"</ul>"
+"<h2> Gravitational Waves  </h2><ul style=\"text-align: left;\">"
+"<li><a href=\"docs/talks/talk-cms.pdf\" target=\"dynamic\"> GW (CMS) </a> </li>"
+"<li><a href=\"docs/talks/talk-ibb.pdf\" target=\"dynamic\"> GW (IBB) </a> </li>"
+"<li><a href=\"docs/talks/talk-mit.pdf\" target=\"dynamic\"> GW (MIT) </a> </li>"
+"</ul>",
"Reports":"<ol style=\"text-align: left;\">"
+"<li> <a href=\"docs/jayanti-phd-thesis.pdf\" target=\"dynamic\"> Ph.D Thesis </a></li>"
+"<li> <a href=\"docs/notes/jp-cosmo-notes.pdf\" target=\"dynamic\"> Cosmology Notes </a></li>"
+"<li> <a href=\"docs/notes/imaging.pdf\" target=\"dynamic\"> Radio Imaging Notes </a></li>"
+"<li> <a href=\"docs/notes/physics-lectures.pdf\" target=\"dynamic\">Physics Notes </a></li>"
+"<li> <a href=\"docs/notes/cmbr.pdf\" target=\"dynamic\"> CMB Notes </a></li>"
+"<li> <a href=\"docs/notes/gwaves.pdf\" target=\"dynamic\"> Gravitational Waves Notes </a></li>"
+"<li> <a href=\"docs/notes/aips.pdf\" target=\"dynamic\"> AIPS Notes </a></li>"
+"<li> <a href=\"docs/notes/matched_filtering.pdf\" target=\"dynamic\"> Matched Filtering  </a></li>"
+"<li> <a href=\"docs/notes/mem.pdf\" target=\"dynamic\"> Maximum Entropy  </a></li>"
+"<li> <a href=\"docs/notes/pulsars.pdf\" target=\"dynamic\"> Radio Pulsars  </a></li>"
+"</ol>"
}

